// scripts/update-excel.js
// HOW THIS WORKS:
//   1. Reads master test cases from test-data/test-cases.csv
//   2. Reads defect log from test-data/defects.csv
//   3. Reads actual pass/fail results from reports/results.json (generated by Playwright)
//   4. Merges all three together
//   5. Writes a formatted Excel file to reports/QA-TestCases-ShopEasy.xlsx
//
// HOW TO ADD A NEW TEST CASE:
//   - Add a row to test-data/test-cases.csv
//   - Write the Playwright spec with the matching TC id in the test title
//   - Run npm test then node scripts/update-excel.js
//   - Done — no changes to this script needed
//
// HOW TO ADD A NEW DEFECT:
//   - Add a row to test-data/defects.csv
//   - Run node scripts/update-excel.js
//   - Done

import ExcelJS from "exceljs";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");

// ── Colour palette ────────────────────────────────────────────────────
const C = {
  headerBg: "2563EB",
  headerFg: "FFFFFF",
  pass: "D1FAE5",
  passText: "065F46",
  fail: "FEE2E2",
  failText: "991B1B",
  skip: "FEF9C3",
  skipText: "713F12",
  notRun: "E0F2FE",
  notRunText: "1E3A5F",
  sectionBg: "EFF6FF",
  border: "CBD5E1",
  white: "FFFFFF",
};

// ── STEP 1: Parse CSV files ───────────────────────────────────────────
// A simple CSV parser — handles the straightforward format we use.
// Rule: no commas inside field values, no quoted fields.

function parseCSV(filePath) {
  const fullPath = path.join(ROOT, filePath);

  if (!fs.existsSync(fullPath)) {
    console.warn(`⚠  File not found: ${filePath}`);
    return [];
  }

  const lines = fs
    .readFileSync(fullPath, "utf8")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0);

  if (lines.length < 2) {
    console.warn(`⚠  CSV has no data rows: ${filePath}`);
    return [];
  }

  // First line = headers, rest = data
  const headers = lines[0].split(",").map((h) => h.trim());

  return lines.slice(1).map((line) => {
    const values = line.split(",").map((v) => v.trim());
    return headers.reduce((obj, header, index) => {
      obj[header] = values[index] || "";
      return obj;
    }, {});
  });
}

// ── STEP 2: Parse Playwright results.json ─────────────────────────────
// This file is auto-generated by Playwright when you run: npm test
// It contains every test, its status, duration, and error message.

function parseResults() {
  const resultsPath = path.join(ROOT, "reports/results.json");

  if (!fs.existsSync(resultsPath)) {
    console.warn("⚠ reports/results.json not found.");
    return {};
  }

  const raw = JSON.parse(fs.readFileSync(resultsPath, "utf8"));
  const map = {};

  function walkSuite(suite) {
    // Process specs in this suite
    (suite.specs || []).forEach((spec) => {
      const match = spec.title.match(/TC-[A-Z0-9-]+/i);
      if (!match) return;

      const tcId = match[0];

      const test = spec.tests?.[0];
      if (!test) return;

      const result = test.results?.[0];
      const passed = test.results?.every((r) => r.status === "passed");

      map[tcId] = {
        status: passed ? "Pass" : "Fail",
        duration: result ? `${(result.duration / 1000).toFixed(1)}s` : "-",
        error:
          result?.error?.message
            ?.split("\n")[0]
            ?.replace(/\x1b\[[0-9;]*m/g, "") || "",
        lastRun: new Date().toLocaleDateString("en-IN"),
      };
    });

    // Recurse into child suites
    (suite.suites || []).forEach(walkSuite);
  }

  (raw.suites || []).forEach(walkSuite);

  return map;
}

// ── STEP 3: Merge CSV with results ───────────────────────────────────
// For each row in the CSV, look up the matching result from Playwright.
// If no result found, status stays 'Not Run'.

function buildTestCases() {
  const masterList = parseCSV("test-data/test-cases.csv");
  const results = parseResults();

  return masterList.map((tc) => ({
    ...tc,
    status: results[tc.id]?.status || "Not Run",
    duration: results[tc.id]?.duration || "-",
    error: results[tc.id]?.error || "",
    lastRun: results[tc.id]?.lastRun || "-",
  }));
}

// ── Excel helpers ─────────────────────────────────────────────────────
const borderStyle = {
  top: { style: "thin", color: { argb: C.border } },
  left: { style: "thin", color: { argb: C.border } },
  bottom: { style: "thin", color: { argb: C.border } },
  right: { style: "thin", color: { argb: C.border } },
};

function styleHeader(cell, text) {
  cell.value = text;
  cell.font = {
    bold: true,
    color: { argb: C.headerFg },
    size: 10,
    name: "Calibri",
  };
  cell.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: C.headerBg },
  };
  cell.alignment = { horizontal: "center", vertical: "middle", wrapText: true };
  cell.border = borderStyle;
}

function statusStyle(status) {
  switch (status) {
    case "Pass":
      return { bg: C.pass, text: C.passText };
    case "Fail":
      return { bg: C.fail, text: C.failText };
    case "Skipped":
      return { bg: C.skip, text: C.skipText };
    default:
      return { bg: C.notRun, text: C.notRunText };
  }
}

function priorityColor(priority) {
  const map = {
    Critical: "FCA5A5",
    High: "FCD34D",
    Medium: "BEF264",
    Low: "D1D5DB",
  };
  return map[priority] || C.white;
}

// ── Sheet 1: Test Cases ───────────────────────────────────────────────
function buildTestCaseSheet(wb, testCases) {
  const ws = wb.addWorksheet("Test Cases", {
    views: [{ state: "frozen", ySplit: 2 }],
  });

  // Column definitions
  const columns = [
    { header: "#", width: 5 },
    { header: "Test ID", width: 16 },
    { header: "Module", width: 18 },
    { header: "Test Case Title", width: 55 },
    { header: "Priority", width: 10 },
    { header: "Type", width: 14 },
    { header: "Automated", width: 10 },
    { header: "Status", width: 11 },
    { header: "Duration", width: 10 },
    { header: "Last Run", width: 14 },
    { header: "Error Message", width: 40 },
  ];

  columns.forEach((col, i) => {
    ws.getColumn(i + 1).width = col.width;
  });

  // Row 1 — title banner spanning all columns
  ws.mergeCells(1, 1, 1, columns.length);
  const titleCell = ws.getCell(1, 1);
  titleCell.value = "🛒  ShopEasy – QA Test Case Tracker";
  titleCell.font = {
    bold: true,
    size: 14,
    color: { argb: C.headerFg },
    name: "Calibri",
  };
  titleCell.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: C.headerBg },
  };
  titleCell.alignment = { horizontal: "center", vertical: "middle" };
  ws.getRow(1).height = 30;

  // Row 2 — column headers
  columns.forEach((col, i) => styleHeader(ws.getCell(2, i + 1), col.header));
  ws.getRow(2).height = 22;

  // Data rows
  let rowNum = 3;
  let rowIndex = 0;
  let currentModule = "";

  testCases.forEach((tc) => {
    // Module separator — insert a shaded row when module changes
    if (tc.module !== currentModule) {
      currentModule = tc.module;
      ws.mergeCells(rowNum, 1, rowNum, columns.length);
      const sep = ws.getCell(rowNum, 1);
      sep.value = `  ${tc.module}`;
      sep.font = {
        bold: true,
        size: 10,
        color: { argb: C.headerBg },
        name: "Calibri",
      };
      sep.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: C.sectionBg },
      };
      sep.alignment = { vertical: "middle" };
      ws.getRow(rowNum).height = 16;
      rowNum++;
    }

    rowIndex++;
    const row = ws.getRow(rowNum);
    row.height = 18;

    const sc = statusStyle(tc.status);
    const values = [
      rowIndex, // #
      tc.id, // Test ID
      tc.module, // Module
      tc.title, // Test Case Title
      tc.priority, // Priority
      tc.type, // Type
      tc.automated, // Automated
      tc.status, // Status
      tc.duration, // Duration — from results.json
      tc.lastRun, // Last Run — from results.json
      tc.error, // Error Message — from results.json
    ];

    values.forEach((value, colIndex) => {
      const cell = row.getCell(colIndex + 1);
      cell.value = value;
      cell.border = borderStyle;
      cell.font = { name: "Calibri", size: 9 };

      // Title (col 3) and Error (col 10) are left-aligned with wrap
      // Everything else is centred
      const isLeftAligned = colIndex === 3 || colIndex === 10;
      cell.alignment = {
        vertical: "middle",
        horizontal: isLeftAligned ? "left" : "center",
        wrapText: isLeftAligned,
      };

      // Status — colour coded background
      if (colIndex === 7) {
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: sc.bg },
        };
        cell.font = {
          bold: true,
          color: { argb: sc.text },
          name: "Calibri",
          size: 9,
        };
      }

      // Priority — colour coded background
      if (colIndex === 4) {
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: priorityColor(tc.priority) },
        };
        cell.font = { bold: true, name: "Calibri", size: 9 };
      }

      // Error message — red italic text
      if (colIndex === 10 && value) {
        cell.font = {
          color: { argb: C.failText },
          name: "Calibri",
          size: 9,
          italic: true,
        };
      }
    });

    rowNum++;
  });

  // Auto-filter so PM/QA lead can filter by module, status, priority
  ws.autoFilter = {
    from: { row: 2, column: 1 },
    to: { row: rowNum - 1, column: columns.length },
  };
}

// ── Sheet 2: Summary ──────────────────────────────────────────────────
function buildSummarySheet(wb, testCases) {
  const ws = wb.addWorksheet("Summary");
  ws.getColumn(1).width = 24;
  ws.getColumn(2).width = 14;

  // Title
  ws.mergeCells("A1:B1");
  const title = ws.getCell("A1");
  title.value = "Test Execution Summary";
  title.font = {
    bold: true,
    size: 13,
    color: { argb: C.headerFg },
    name: "Calibri",
  };
  title.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: C.headerBg },
  };
  title.alignment = { horizontal: "center", vertical: "middle" };
  ws.getRow(1).height = 28;

  // Calculate counts
  const total = testCases.length;
  const passed = testCases.filter((t) => t.status === "Pass").length;
  const failed = testCases.filter((t) => t.status === "Fail").length;
  const skipped = testCases.filter((t) => t.status === "Skipped").length;
  const notRun = testCases.filter((t) => t.status === "Not Run").length;
  const passRate = total > 0 ? ((passed / total) * 100).toFixed(1) : "0.0";
  const generatedAt = new Date().toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const rows = [
    { label: "Metric", value: "Count", isHeader: true },
    { label: "Total Test Cases", value: total },
    { label: "Passed ✅", value: passed, bg: C.pass },
    { label: "Failed ❌", value: failed, bg: C.fail },
    { label: "Skipped ⏭", value: skipped, bg: C.skip },
    { label: "Not Run 🔵", value: notRun, bg: C.notRun },
    { label: "Pass Rate", value: `${passRate}%` },
    { label: "Generated At", value: generatedAt },
  ];

  rows.forEach((rowData, i) => {
    const rowNum = i + 2;
    const c1 = ws.getCell(rowNum, 1);
    const c2 = ws.getCell(rowNum, 2);

    c1.value = rowData.label;
    c2.value = rowData.value;

    [c1, c2].forEach((c) => {
      c.border = borderStyle;
      c.font = { name: "Calibri", size: 10 };
      c.alignment = { vertical: "middle" };
    });
    c2.alignment = { horizontal: "center", vertical: "middle" };
    ws.getRow(rowNum).height = 20;

    if (rowData.isHeader) {
      [c1, c2].forEach((c) => {
        c.font = {
          bold: true,
          color: { argb: C.headerFg },
          name: "Calibri",
          size: 10,
        };
        c.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: C.headerBg },
        };
      });
    }

    if (rowData.bg) {
      c2.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: rowData.bg },
      };
    }
  });

  // Per-module breakdown
  let mr = 12;

  ["Module", "Pass / Total"].forEach((h, i) => {
    const c = ws.getCell(mr, i + 1);
    c.value = h;
    c.font = {
      bold: true,
      color: { argb: C.headerFg },
      name: "Calibri",
      size: 10,
    };
    c.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: C.headerBg },
    };
    c.border = borderStyle;
    c.alignment = { horizontal: "center", vertical: "middle" };
  });
  mr++;

  // Unique modules in CSV order
  const modules = [...new Set(testCases.map((t) => t.module))];

  modules.forEach((mod) => {
    const modCases = testCases.filter((t) => t.module === mod);
    const modPass = modCases.filter((t) => t.status === "Pass").length;
    const modFail = modCases.filter((t) => t.status === "Fail").length;

    const c1 = ws.getCell(mr, 1);
    const c2 = ws.getCell(mr, 2);

    c1.value = mod;
    c2.value = `${modPass} / ${modCases.length}`;

    [c1, c2].forEach((c) => {
      c.border = borderStyle;
      c.font = { name: "Calibri", size: 9 };
      c.alignment = { vertical: "middle" };
    });
    c2.alignment = { horizontal: "center", vertical: "middle" };

    // Highlight module rows that have failures in light red
    if (modFail > 0) {
      [c1, c2].forEach((c) => {
        c.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: { argb: "FEF2F2" },
        };
      });
      c2.font = {
        bold: true,
        color: { argb: C.failText },
        name: "Calibri",
        size: 9,
      };
    }

    mr++;
  });
}

// ── Sheet 3: Defect Log ───────────────────────────────────────────────
function buildDefectSheet(wb) {
  const defects = parseCSV("test-data/defects.csv");
  const ws = wb.addWorksheet("Defect Log");

  const columns = [
    { header: "Defect ID", width: 12 },
    { header: "TC ID", width: 14 },
    { header: "Module", width: 18 },
    { header: "Summary", width: 50 },
    { header: "Severity", width: 11 },
    { header: "Priority", width: 10 },
    { header: "Status", width: 13 },
    { header: "Reported By", width: 16 },
    { header: "Date", width: 13 },
    { header: "Jira Link", width: 14 },
    { header: "Remarks", width: 35 },
  ];

  columns.forEach((col, i) => {
    ws.getColumn(i + 1).width = col.width;
  });

  // Title
  ws.mergeCells(1, 1, 1, columns.length);
  const title = ws.getCell(1, 1);
  title.value = "🐛  ShopEasy – Defect Log";
  title.font = {
    bold: true,
    size: 13,
    color: { argb: C.headerFg },
    name: "Calibri",
  };
  title.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: C.headerBg },
  };
  title.alignment = { horizontal: "center", vertical: "middle" };
  ws.getRow(1).height = 28;

  // Headers
  columns.forEach((col, i) => styleHeader(ws.getCell(2, i + 1), col.header));
  ws.getRow(2).height = 22;

  // Data rows from defects.csv
  defects.forEach((defect, i) => {
    const rowNum = i + 3;
    const row = ws.getRow(rowNum);
    row.height = 18;

    const values = [
      defect.id,
      defect.tcId,
      defect.module,
      defect.summary,
      defect.severity,
      defect.priority,
      defect.status,
      defect.reportedBy,
      defect.date,
      defect.jiraLink,
      defect.remarks,
    ];

    values.forEach((value, colIndex) => {
      const cell = row.getCell(colIndex + 1);
      cell.value = value;
      cell.border = borderStyle;
      cell.font = { name: "Calibri", size: 9 };

      const isLeftAligned = colIndex === 3 || colIndex === 10;
      cell.alignment = {
        vertical: "middle",
        horizontal: isLeftAligned ? "left" : "center",
        wrapText: isLeftAligned,
      };

      // Status colour — Open/In Progress/Fixed/Closed
      if (colIndex === 6) {
        const sc = {
          Open: { bg: C.fail, text: C.failText },
          "In Progress": { bg: C.skip, text: C.skipText },
          Fixed: { bg: C.pass, text: C.passText },
          Closed: { bg: C.notRun, text: C.notRunText },
        }[value];
        if (sc) {
          cell.fill = {
            type: "pattern",
            pattern: "solid",
            fgColor: { argb: sc.bg },
          };
          cell.font = {
            bold: true,
            color: { argb: sc.text },
            name: "Calibri",
            size: 9,
          };
        }
      }

      // Severity colour
      if (colIndex === 4) {
        const sc = priorityColor(value);
        if (sc !== C.white) {
          cell.fill = {
            type: "pattern",
            pattern: "solid",
            fgColor: { argb: sc },
          };
          cell.font = { bold: true, name: "Calibri", size: 9 };
        }
      }
    });
  });

  if (defects.length > 0) {
    ws.autoFilter = {
      from: { row: 2, column: 1 },
      to: { row: defects.length + 2, column: columns.length },
    };
  }
}

// ── Main ──────────────────────────────────────────────────────────────
async function main() {
  console.log("\n📊  ShopEasy Excel Tracker\n");

  console.log("  ① Reading test-data/test-cases.csv...");
  const testCases = buildTestCases();
  const passed = testCases.filter((t) => t.status === "Pass").length;
  const failed = testCases.filter((t) => t.status === "Fail").length;
  const notRun = testCases.filter((t) => t.status === "Not Run").length;
  console.log(
    `     ${testCases.length} test cases — Pass: ${passed} | Fail: ${failed} | Not Run: ${notRun}`,
  );

  console.log("\n  ② Reading test-data/defects.csv...");
  const defects = parseCSV("test-data/defects.csv");
  console.log(`     ${defects.length} defects`);

  console.log("\n  ③ Building Excel workbook...");
  const wb = new ExcelJS.Workbook();
  wb.creator = "ShopEasy QA";
  wb.created = new Date();
  wb.modified = new Date();

  buildTestCaseSheet(wb, testCases);
  console.log("     ✓ Sheet 1: Test Cases");

  buildSummarySheet(wb, testCases);
  console.log("     ✓ Sheet 2: Summary");

  buildDefectSheet(wb);
  console.log("     ✓ Sheet 3: Defect Log");

  const outPath = path.join(ROOT, "reports/QA-TestCases-ShopEasy.xlsx");
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  await wb.xlsx.writeFile(outPath);

  console.log(`\n✅  Saved → reports/QA-TestCases-ShopEasy.xlsx`);
  console.log("\n   Next time you add a test:");
  console.log("   1. Add a row to test-data/test-cases.csv");
  console.log("   2. Write the spec with the TC id in the test name");
  console.log("   3. Run: npm test && node scripts/update-excel.js\n");
}

main().catch((err) => {
  console.error("❌ Error:", err.message);
  process.exit(1);
});
